<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Spare Parts Replacement History Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 15px; color: #333; background: #fff; font-size: 10px; }
        .header { margin-bottom: 20px; border-bottom: 3px solid #fd7e14; padding-bottom: 15px; }
        .header-content { display: table; width: 100%; }
        .logo-section { display: table-cell; width: 120px; vertical-align: middle; }
        .company-logo { height: 70px; max-width: 120px; object-fit: contain; }
        .title-section { display: table-cell; text-align: center; vertical-align: middle; }
        .header h1 { color: #fd7e14; margin: 0; font-size: 20px; }
        .company-name { color: #333; margin: 5px 0; font-size: 14px; font-weight: 600; }
        .subtitle { color: #666; font-size: 12px; }
        .report-info { background: #f8f9fa; padding: 10px; margin-bottom: 12px; border-left: 4px solid #fd7e14; }
        .report-info h3 { margin: 0 0 8px 0; color: #fd7e14; font-size: 14px; }
        .data-table { width: 100%; border-collapse: collapse; font-size: 8px; }
        .data-table thead { background: #fd7e14; color: white; }
        .data-table th { padding: 6px 4px; text-align: left; font-weight: bold; }
        .data-table td { padding: 4px; border-bottom: 1px solid #dee2e6; }
        .data-table tfoot { background: #f8f9fa; font-weight: bold; border-top: 2px solid #fd7e14; }
        .text-end { text-align: right; }
        .footer { margin-top: 30px; text-align: center; color: #666; font-size: 10px; border-top: 1px solid #dee2e6; padding-top: 15px; }
        .no-data { text-align: center; padding: 30px; color: #666; font-style: italic; }
        .summary-box { background: #f8f9fa; padding: 12px; margin-bottom: 12px; }
        .summary-value { font-size: 16px; font-weight: bold; color: #fd7e14; }
    </style>
</head>
<body>
    <div class="header">
        <div class="header-content">
            <div class="logo-section">
                @if($company && $company->logo)
                    <img src="{{ public_path('storage/' . $company->logo) }}" alt="{{ $company->name }}" class="company-logo">
                @endif
            </div>
            <div class="title-section">
                <h1>Spare Parts Replacement History Report</h1>
                @if($company)<div class="company-name">{{ $company->name }}</div>@endif
                <div class="subtitle">Generated on {{ $generatedAt->format('F d, Y \a\t g:i A') }}</div>
            </div>
        </div>
    </div>
    <div class="report-info">
        <h3>Report Parameters</h3>
        Period: {{ $dateFrom->format('M d, Y') }} - {{ $dateTo->format('M d, Y') }}
        @if($branch)<br>Branch: {{ $branch->name }}@endif
    </div>
    @if($replacements->count() > 0)
        <div class="summary-box">
            Total Replacements: <span class="summary-value">{{ $replacements->count() }}</span>
            | Total Cost (TZS): <span class="summary-value">{{ number_format($totalCost, 2) }}</span>
        </div>
        <table class="data-table">
            <thead>
                <tr>
                    <th>S/N</th><th>Date</th><th>Vehicle</th><th>Spare Part</th><th class="text-end">Cost</th>
                    <th class="text-end">Odometer</th><th>Reason</th><th>Approved By</th><th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($replacements as $index => $r)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $r->replaced_at ? $r->replaced_at->format('Y-m-d') : 'N/A' }}</td>
                    <td>{{ $r->vehicle ? $r->vehicle->name : 'N/A' }}</td>
                    <td>{{ $r->sparePartCategory ? $r->sparePartCategory->name : 'N/A' }}</td>
                    <td class="text-end">{{ number_format($r->cost ?? 0, 0) }}</td>
                    <td class="text-end">{{ $r->odometer_at_replacement ? number_format($r->odometer_at_replacement, 0) : 'N/A' }}</td>
                    <td>{{ Str::limit($r->reason ?? 'N/A', 30) }}</td>
                    <td>{{ $r->approvedBy ? $r->approvedBy->name : 'N/A' }}</td>
                    <td>{{ $r->status ?? 'N/A' }}</td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="4" class="text-end">TOTAL:</td>
                    <td class="text-end">{{ number_format($replacements->sum('cost'), 0) }}</td>
                    <td colspan="4"></td>
                </tr>
            </tfoot>
        </table>
    @else
        <div class="no-data">No spare parts replacements found for the selected period.</div>
    @endif
    <div class="footer">
        <p>This report was generated by Smart Accounting System. Report ID: {{ strtoupper(uniqid()) }}</p>
    </div>
</body>
</html>
