<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Spare Parts Cost Analysis Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 15px; color: #333; background: #fff; font-size: 10px; }
        .header { margin-bottom: 20px; border-bottom: 3px solid #fd7e14; padding-bottom: 15px; }
        .header-content { display: table; width: 100%; }
        .logo-section { display: table-cell; width: 120px; vertical-align: middle; }
        .company-logo { height: 70px; max-width: 120px; object-fit: contain; }
        .title-section { display: table-cell; text-align: center; vertical-align: middle; }
        .header h1 { color: #fd7e14; margin: 0; font-size: 20px; }
        .company-name { color: #333; margin: 5px 0; font-size: 14px; font-weight: 600; }
        .subtitle { color: #666; font-size: 12px; }
        .report-info { background: #f8f9fa; padding: 10px; margin-bottom: 12px; border-left: 4px solid #fd7e14; }
        .report-info h3 { margin: 0 0 8px 0; color: #fd7e14; font-size: 14px; }
        .data-table { width: 100%; border-collapse: collapse; font-size: 10px; }
        .data-table thead { background: #fd7e14; color: white; }
        .data-table th { padding: 8px 6px; text-align: left; font-weight: bold; }
        .data-table td { padding: 6px; border-bottom: 1px solid #dee2e6; }
        .data-table tfoot { background: #f8f9fa; font-weight: bold; border-top: 2px solid #fd7e14; }
        .text-end { text-align: right; }
        .footer { margin-top: 30px; text-align: center; color: #666; font-size: 10px; border-top: 1px solid #dee2e6; padding-top: 15px; }
        .no-data { text-align: center; padding: 30px; color: #666; font-style: italic; }
        .summary-box { background: #f8f9fa; padding: 12px; margin-bottom: 12px; }
        .summary-value { font-size: 16px; font-weight: bold; color: #fd7e14; }
    </style>
</head>
<body>
    <div class="header">
        <div class="header-content">
            <div class="logo-section">
                @if($company && $company->logo)
                    <img src="{{ public_path('storage/' . $company->logo) }}" alt="{{ $company->name }}" class="company-logo">
                @endif
            </div>
            <div class="title-section">
                <h1>Spare Parts Cost Analysis Report</h1>
                @if($company)<div class="company-name">{{ $company->name }}</div>@endif
                <div class="subtitle">Generated on {{ $generatedAt->format('F d, Y \a\t g:i A') }}</div>
            </div>
        </div>
    </div>
    <div class="report-info">
        <h3>Report Parameters</h3>
        Period: {{ $dateFrom->format('M d, Y') }} - {{ $dateTo->format('M d, Y') }}
        @if($branch)<br>Branch: {{ $branch->name }}@endif
    </div>
    @if($costData->count() > 0)
        <div class="summary-box">
            Total Cost (TZS): <span class="summary-value">{{ number_format($totalCost, 2) }}</span>
            | Total Replacements: <span class="summary-value">{{ $totalReplacements }}</span>
            | Vehicles: <span class="summary-value">{{ $costData->count() }}</span>
        </div>
        <table class="data-table">
            <thead>
                <tr>
                    <th>S/N</th><th>Vehicle</th><th class="text-end">Total Cost (TZS)</th><th class="text-end">Replacement Count</th><th class="text-end">Avg Cost/Replacement</th>
                </tr>
            </thead>
            <tbody>
                @foreach($costData as $index => $row)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $row->vehicle }}</td>
                    <td class="text-end">{{ number_format($row->total_cost, 0) }}</td>
                    <td class="text-end">{{ $row->replacement_count }}</td>
                    <td class="text-end">{{ number_format($row->avg_cost_per_replacement, 0) }}</td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <th></th><th class="text-end">TOTAL:</th>
                    <th class="text-end">{{ number_format($costData->sum('total_cost'), 0) }}</th>
                    <th class="text-end">{{ $costData->sum('replacement_count') }}</th>
                    <th class="text-end">{{ number_format($costData->avg('avg_cost_per_replacement'), 0) }}</th>
                </tr>
            </tfoot>
        </table>
    @else
        <div class="no-data">No spare parts cost data available for the selected period.</div>
    @endif
    <div class="footer">
        <p>This report was generated by Smart Accounting System. Report ID: {{ strtoupper(uniqid()) }}</p>
    </div>
</body>
</html>
