<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tyre Cost & Efficiency Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 15px; color: #333; background: #fff; font-size: 10px; }
        .header { margin-bottom: 20px; border-bottom: 3px solid #6f42c1; padding-bottom: 15px; }
        .header-content { display: table; width: 100%; }
        .logo-section { display: table-cell; width: 120px; vertical-align: middle; }
        .company-logo { height: 70px; max-width: 120px; object-fit: contain; }
        .title-section { display: table-cell; text-align: center; vertical-align: middle; }
        .header h1 { color: #6f42c1; margin: 0; font-size: 20px; }
        .company-name { color: #333; margin: 5px 0; font-size: 14px; font-weight: 600; }
        .subtitle { color: #666; font-size: 12px; }
        .report-info { background: #f8f9fa; padding: 10px; margin-bottom: 12px; border-left: 4px solid #6f42c1; }
        .report-info h3 { margin: 0 0 8px 0; color: #6f42c1; font-size: 14px; }
        .data-table { width: 100%; border-collapse: collapse; font-size: 9px; }
        .data-table thead { background: #6f42c1; color: white; }
        .data-table th { padding: 6px 4px; text-align: left; font-weight: bold; }
        .data-table td { padding: 4px; border-bottom: 1px solid #dee2e6; }
        .data-table tfoot { background: #f8f9fa; font-weight: bold; border-top: 2px solid #6f42c1; }
        .text-end { text-align: right; }
        .footer { margin-top: 30px; text-align: center; color: #666; font-size: 10px; border-top: 1px solid #dee2e6; padding-top: 15px; }
        .no-data { text-align: center; padding: 30px; color: #666; font-style: italic; }
        .summary-box { background: #f8f9fa; padding: 12px; margin-bottom: 12px; }
        .summary-value { font-size: 16px; font-weight: bold; color: #6f42c1; }
    </style>
</head>
<body>
    <div class="header">
        <div class="header-content">
            <div class="logo-section">
                @if($company && $company->logo)
                    <img src="{{ public_path('storage/' . $company->logo) }}" alt="{{ $company->name }}" class="company-logo">
                @endif
            </div>
            <div class="title-section">
                <h1>Tyre Cost & Efficiency Report</h1>
                @if($company)<div class="company-name">{{ $company->name }}</div>@endif
                <div class="subtitle">Generated on {{ $generatedAt->format('F d, Y \a\t g:i A') }}</div>
            </div>
        </div>
    </div>
    <div class="report-info">
        <h3>Report Parameters</h3>
        Period: {{ $dateFrom->format('M d, Y') }} - {{ $dateTo->format('M d, Y') }}
        @if($branch)<br>Branch: {{ $branch->name }}@endif
    </div>
    @if($tyreData->count() > 0)
        <div class="summary-box">
            Total Cost (TZS): <span class="summary-value">{{ number_format($totalCost, 2) }}</span>
            | Total KM: <span class="summary-value">{{ number_format($totalKm, 0) }}</span>
            | Tyres: <span class="summary-value">{{ $tyreData->count() }}</span>
        </div>
        <table class="data-table">
            <thead>
                <tr>
                    <th>S/N</th><th>Serial</th><th>Brand</th><th class="text-end">Purchase Cost</th><th class="text-end">Total KM</th>
                    <th class="text-end">Cost/KM</th><th class="text-end">Expected KM</th><th>Efficiency %</th>
                </tr>
            </thead>
            <tbody>
                @foreach($tyreData as $index => $tyre)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $tyre->serial_number }}</td>
                    <td>{{ $tyre->brand }}</td>
                    <td class="text-end">{{ number_format($tyre->purchase_cost, 0) }}</td>
                    <td class="text-end">{{ number_format($tyre->total_km, 0) }}</td>
                    <td class="text-end">{{ number_format($tyre->cost_per_km, 2) }}</td>
                    <td class="text-end">{{ number_format($tyre->expected_lifespan_km, 0) }}</td>
                    <td>{{ $tyre->efficiency_rating }}%</td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-end">TOTAL:</td>
                    <td class="text-end">{{ number_format($tyreData->sum('purchase_cost'), 0) }}</td>
                    <td class="text-end">{{ number_format($tyreData->sum('total_km'), 0) }}</td>
                    <td colspan="3"></td>
                </tr>
            </tfoot>
        </table>
    @else
        <div class="no-data">No tyre cost data available for the selected period.</div>
    @endif
    <div class="footer">
        <p>This report was generated by Smart Accounting System. Report ID: {{ strtoupper(uniqid()) }}</p>
    </div>
</body>
</html>
