<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tyre Abuse & Warranty Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 15px; color: #333; background: #fff; font-size: 10px; }
        .header { margin-bottom: 20px; border-bottom: 3px solid #dc3545; padding-bottom: 15px; }
        .header-content { display: table; width: 100%; }
        .logo-section { display: table-cell; width: 120px; vertical-align: middle; }
        .company-logo { height: 70px; max-width: 120px; object-fit: contain; }
        .title-section { display: table-cell; text-align: center; vertical-align: middle; }
        .header h1 { color: #dc3545; margin: 0; font-size: 20px; }
        .company-name { color: #333; margin: 5px 0; font-size: 14px; font-weight: 600; }
        .subtitle { color: #666; font-size: 12px; }
        .report-info { background: #f8f9fa; padding: 10px; margin-bottom: 12px; border-left: 4px solid #dc3545; }
        .data-table { width: 100%; border-collapse: collapse; font-size: 9px; }
        .data-table thead { background: #dc3545; color: white; }
        .data-table th { padding: 6px 4px; text-align: left; font-weight: bold; }
        .data-table td { padding: 4px; border-bottom: 1px solid #dee2e6; }
        .text-end { text-align: right; }
        .footer { margin-top: 30px; text-align: center; color: #666; font-size: 10px; border-top: 1px solid #dee2e6; padding-top: 15px; }
        .no-data { text-align: center; padding: 30px; color: #666; font-style: italic; }
    </style>
</head>
<body>
    <div class="header">
        <div class="header-content">
            <div class="logo-section">
                @if($company && $company->logo)
                    <img src="{{ public_path('storage/' . $company->logo) }}" alt="{{ $company->name }}" class="company-logo">
                @endif
            </div>
            <div class="title-section">
                <h1>Tyre Abuse & Warranty Report</h1>
                @if($company)<div class="company-name">{{ $company->name }}</div>@endif
                <div class="subtitle">Generated on {{ $generatedAt->format('F d, Y \a\t g:i A') }}</div>
            </div>
        </div>
    </div>
    <div class="report-info">
        <h3>Report</h3>
        Premature tyre failures (less than 50% of expected lifespan).
        @if($branch)<br>Branch: {{ $branch->name }}@endif
    </div>
    @if($abuseData->count() > 0)
        <table class="data-table">
            <thead>
                <tr>
                    <th>S/N</th><th>Tyre Serial</th><th>Vehicle</th><th>Requested By</th>
                    <th class="text-end">KM Covered</th><th class="text-end">Expected KM</th><th>Failure %</th><th>Reason</th><th>Request Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($abuseData as $index => $abuse)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $abuse->tyre_serial }}</td>
                    <td>{{ $abuse->vehicle }}</td>
                    <td>{{ $abuse->requested_by }}</td>
                    <td class="text-end">{{ number_format($abuse->km_covered, 0) }}</td>
                    <td class="text-end">{{ number_format($abuse->expected_km, 0) }}</td>
                    <td>{{ $abuse->failure_pct }}%</td>
                    <td>{{ $abuse->reason }}</td>
                    <td>{{ $abuse->request_date }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">No premature tyre failures detected.</div>
    @endif
    <div class="footer">
        <p>This report was generated by Smart Accounting System. Report ID: {{ strtoupper(uniqid()) }}</p>
    </div>
</body>
</html>
