<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tyre Installation Log Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 15px; color: #333; background: #fff; font-size: 10px; }
        .header { margin-bottom: 20px; border-bottom: 3px solid #0dcaf0; padding-bottom: 15px; }
        .header-content { display: table; width: 100%; }
        .logo-section { display: table-cell; width: 120px; vertical-align: middle; }
        .company-logo { height: 70px; max-width: 120px; object-fit: contain; }
        .title-section { display: table-cell; text-align: center; vertical-align: middle; }
        .header h1 { color: #0dcaf0; margin: 0; font-size: 20px; }
        .company-name { color: #333; margin: 5px 0; font-size: 14px; font-weight: 600; }
        .subtitle { color: #666; font-size: 12px; }
        .report-info { background: #f8f9fa; padding: 10px; margin-bottom: 12px; border-left: 4px solid #0dcaf0; }
        .report-info h3 { margin: 0 0 8px 0; color: #0dcaf0; font-size: 14px; }
        .data-table { width: 100%; border-collapse: collapse; font-size: 9px; }
        .data-table thead { background: #0dcaf0; color: #333; }
        .data-table th { padding: 6px 4px; text-align: left; font-weight: bold; }
        .data-table td { padding: 4px; border-bottom: 1px solid #dee2e6; }
        .text-end { text-align: right; }
        .footer { margin-top: 30px; text-align: center; color: #666; font-size: 10px; border-top: 1px solid #dee2e6; padding-top: 15px; }
        .no-data { text-align: center; padding: 30px; color: #666; font-style: italic; }
        .summary-box { background: #f8f9fa; padding: 12px; margin-bottom: 12px; }
        .summary-value { font-size: 16px; font-weight: bold; color: #0dcaf0; }
    </style>
</head>
<body>
    <div class="header">
        <div class="header-content">
            <div class="logo-section">
                @if($company && $company->logo)
                    <img src="{{ public_path('storage/' . $company->logo) }}" alt="{{ $company->name }}" class="company-logo">
                @endif
            </div>
            <div class="title-section">
                <h1>Tyre Installation & Removal Log Report</h1>
                @if($company)<div class="company-name">{{ $company->name }}</div>@endif
                <div class="subtitle">Generated on {{ $generatedAt->format('F d, Y \a\t g:i A') }}</div>
            </div>
        </div>
    </div>
    <div class="report-info">
        <h3>Report Parameters</h3>
        Period: {{ $dateFrom->format('M d, Y') }} - {{ $dateTo->format('M d, Y') }}
        @if($branch)<br>Branch: {{ $branch->name }}@endif
    </div>
    @if($installations->count() > 0)
        <div class="summary-box">
            Total Installations: <span class="summary-value">{{ $installations->count() }}</span>
        </div>
        <table class="data-table">
            <thead>
                <tr>
                    <th>S/N</th><th>Installation Date</th><th>Tyre Serial</th><th>Vehicle</th><th>Position</th><th class="text-end">Odometer at Install</th><th>Installer</th>
                </tr>
            </thead>
            <tbody>
                @foreach($installations as $index => $i)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $i->installed_at ? $i->installed_at->format('Y-m-d') : 'N/A' }}</td>
                    <td>{{ $i->tyre ? $i->tyre->tyre_serial : 'N/A' }}</td>
                    <td>{{ $i->vehicle ? $i->vehicle->name : 'N/A' }}</td>
                    <td>{{ $i->tyrePosition ? $i->tyrePosition->name : 'N/A' }}</td>
                    <td class="text-end">{{ $i->odometer_at_install ? number_format($i->odometer_at_install, 0) : 'N/A' }}</td>
                    <td>{{ $i->installer_name ?? 'N/A' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">No tyre installation records found for the selected period.</div>
    @endif
    <div class="footer">
        <p>This report was generated by Smart Accounting System. Report ID: {{ strtoupper(uniqid()) }}</p>
    </div>
</body>
</html>
