<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Capital Work in Progress (CWIP) Report</title>
    <style>
        body { font-family: 'Helvetica', 'DejaVu Sans', sans-serif; margin: 0; padding: 15px; color: #333; }
        .header { margin-bottom: 20px; border-bottom: 3px solid #6c757d; padding-bottom: 15px; text-align: center; }
        .header h1 { color: #6c757d; margin: 0; font-size: 24px; font-weight: bold; }
        .header .subtitle { color: #666; margin: 5px 0 0 0; font-size: 14px; }
        .summary-stats { display: table; width: 100%; margin-bottom: 15px; background: #fff; border: 1px solid #dee2e6; border-radius: 8px; overflow: hidden; }
        .stat-item { display: table-cell; text-align: center; padding: 12px 8px; border-right: 1px solid #dee2e6; background: #f8f9fa; }
        .stat-item:last-child { border-right: none; }
        .stat-value { font-size: 16px; font-weight: bold; color: #6c757d; margin: 0; }
        .stat-label { font-size: 10px; color: #666; margin: 3px 0 0 0; text-transform: uppercase; }
        .data-table { width: 100%; border-collapse: collapse; margin-top: 20px; background: #fff; }
        .data-table thead { background: #6c757d; color: white; }
        .data-table th { padding: 8px 6px; text-align: left; font-weight: bold; font-size: 10px; }
        .data-table td { padding: 8px 6px; border-bottom: 1px solid #dee2e6; font-size: 10px; }
        .number { text-align: right; font-family: 'Courier', 'Courier New', monospace; }
        .totals-row { background: #fff3cd !important; font-weight: bold; }
        .totals-row td { border-top: 2px solid #ffc107 !important; padding: 10px 6px !important; }
        .footer { margin-top: 40px; text-align: center; color: #666; font-size: 12px; border-top: 1px solid #dee2e6; padding-top: 20px; }
        .note { background: #d1ecf1; padding: 10px; border-left: 4px solid #17a2b8; margin-bottom: 15px; font-size: 11px; color: #0c5460; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Capital Work in Progress (CWIP) Report</h1>
        <div class="subtitle">Generated on {{ now()->format('F d, Y \a\t g:i A') }}</div>
    </div>

    @if(count($data) > 0)
        <div class="summary-stats">
            <div class="stat-item">
                <div class="stat-value">{{ number_format($summary['count']) }}</div>
                <div class="stat-label">Total Projects</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">{{ number_format($summary['total_balance'], 2) }}</div>
                <div class="stat-label">Total CWIP Balance (TZS)</div>
            </div>
        </div>

        <div class="note">
            <strong>CWIP:</strong> Tracks assets currently under construction or development that have not yet been placed in service.
        </div>

        <table class="data-table">
            <thead>
                <tr>
                    <th>Project Code</th>
                    <th>Project Name</th>
                    <th class="number">Opening Balance</th>
                    <th class="number">Additions</th>
                    <th class="number">Capitalized</th>
                    <th class="number">Closing Balance</th>
                    <th>Expected Completion</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $item)
                <tr>
                    <td>{{ $item['project_code'] }}</td>
                    <td>{{ $item['project_name'] }}</td>
                    <td class="number">{{ number_format($item['opening_balance'], 2) }}</td>
                    <td class="number">{{ number_format($item['additions'], 2) }}</td>
                    <td class="number">{{ number_format($item['capitalized'], 2) }}</td>
                    <td class="number"><strong>{{ number_format($item['closing_balance'], 2) }}</strong></td>
                    <td>{{ $item['expected_completion_date'] }}</td>
                </tr>
                @endforeach
                
                <tr class="totals-row">
                    <td colspan="5" class="number"><strong>TOTAL</strong></td>
                    <td class="number"><strong>{{ number_format($summary['total_balance'], 2) }}</strong></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    @else
        <div style="text-align: center; padding: 40px; color: #666; font-style: italic;">
            <h3>No Data Available</h3>
            <p>No CWIP projects found.</p>
        </div>
    @endif

    <div class="footer">
        <p>This report was generated by Smart Accounting System</p>
    </div>
</body>
</html>
