<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Physical Verification Report</title>
    <style>
        body { font-family: 'Helvetica', 'DejaVu Sans', sans-serif; margin: 0; padding: 15px; color: #333; }
        .header { margin-bottom: 20px; border-bottom: 3px solid #ffc107; padding-bottom: 15px; text-align: center; }
        .header h1 { color: #ffc107; margin: 0; font-size: 24px; font-weight: bold; }
        .header .subtitle { color: #666; margin: 5px 0 0 0; font-size: 14px; }
        .note { background: #fff3cd; padding: 10px; border-left: 4px solid #ffc107; margin-bottom: 15px; font-size: 11px; color: #856404; }
        .data-table { width: 100%; border-collapse: collapse; margin-top: 20px; background: #fff; }
        .data-table thead { background: #ffc107; color: #333; }
        .data-table th { padding: 8px 6px; text-align: left; font-weight: bold; font-size: 10px; }
        .data-table td { padding: 8px 6px; border-bottom: 1px solid #dee2e6; font-size: 10px; }
        .badge { padding: 3px 8px; border-radius: 3px; font-size: 9px; font-weight: bold; }
        .badge-success { background: #d4edda; color: #155724; }
        .badge-secondary { background: #e2e3e5; color: #383d41; }
        .footer { margin-top: 40px; text-align: center; color: #666; font-size: 12px; border-top: 1px solid #dee2e6; padding-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Physical Verification Report</h1>
        <div class="subtitle">Generated on {{ now()->format('F d, Y \a\t g:i A') }}</div>
    </div>

    <div class="note">
        <strong>Purpose:</strong> This report is used during physical stock-take exercises to verify the existence and condition of fixed assets. 
        Please check each asset physically and update the verification status accordingly.
    </div>

    @if(count($data) > 0)
        <table class="data-table">
            <thead>
                <tr>
                    <th>Asset Code</th>
                    <th>Asset Name</th>
                    <th>Location</th>
                    <th>System Status</th>
                    <th>Physical Status</th>
                    <th>Variance</th>
                    <th>Verified By</th>
                    <th>Verification Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $item)
                <tr>
                    <td>{{ $item['asset_code'] }}</td>
                    <td>{{ $item['asset_name'] }}</td>
                    <td>{{ $item['location'] }}</td>
                    <td><span class="badge badge-success">{{ $item['system_status'] }}</span></td>
                    <td><span class="badge badge-secondary">{{ $item['physical_status'] }}</span></td>
                    <td>{{ $item['variance'] }}</td>
                    <td>{{ $item['verified_by'] }}</td>
                    <td>{{ $item['verification_date'] }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div style="text-align: center; padding: 40px; color: #666; font-style: italic;">
            <h3>No Data Available</h3>
            <p>No assets found for verification.</p>
        </div>
    @endif

    <div class="footer">
        <p>This report was generated by Smart Accounting System</p>
        <p><strong>Total Assets to Verify:</strong> {{ count($data) }}</p>
    </div>
</body>
</html>
